### ISSUE TITLE
Remove support for custom exceptions

### ISSUE THREAD

**Issue by joshuaflanagan** [jorgemanrubia/solid_assert#2]
I think it was a mistake to merge https://github.com/jorgemanrubia/solid_assert/commit/d59b1c00f9be88191d2c95a7db3caf19c18d42e9.

- It unnecessarily complicates a formerly simple library
- More importantly, I think it gives people the wrong impression on how to properly use assertions. Assertions are intended to be different from raising exception for normal runtime errors. As stated in [the StackOverlow answer that led me to this gem](http://stackoverflow.com/a/7481328):

> Regarding to the answer saying that the idiomatic Ruby way is using a normal raise statement, I think it lacks of expressivity. One of the golden rules of assertive programming is not using assertions for normal exception handling. They are two completely different things. If you use the same syntax for the two of them, I think you code will be more obscure. And of course you lose the capability of deactivating them.

Since you shouldn't be using assertions for normal exception handling, and you certainly shouldn't be `rescue`ing any assertions, I see no good reason to need any other exception than the provided `AssertionFailedError`.

**Comment by 907th** [comment]
@joshuaflanagan Yeah, may be you are right. I was never disabling assertions in production and used it as a "better raise/fail" (part of a normal exceptions handling). So I found it very useful to add support for custom exception classes.

@jorgemanrubia What would you say?

**Comment by joshuaflanagan** [comment]
@907th Okay, I don't think you need a library for that scenario. Use: `raise CustomeException if condition`. Much clearer intent.

**Comment by franklinyu** [comment]
Exception is used when an application or gem is used improperly (which is expected); assertion is used by the author of the application or gem when unexpected situation happens, i.e., programming error.
